name: brain-diffuser
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - pytorch
  - torchvision
  - scikit-learn
  - matplotlib
  - ipython
  - jupyter
  - spyder
  - nbconvert
  - scipy
  - ffmpeg
  - cudatoolkit=11.3
  - pip:
      - absl-py==1.3.0
      - antlr4-python3-runtime==4.8
      - anyio==3.6.2
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - clip==1.0
      - cycler==0.11.0
      - easydict==1.9
      - einops==0.3.0
      - filelock==3.8.0
      - fire==0.4.0
      - ftfy==6.1.1
      - gauss==0.0.9
      - grpcio==1.50.0
      - h5py==3.7.0
      - huggingface-hub==0.11.0
      - imageio==2.22.4
      - importlib-metadata==5.0.0
      - ipykernel==5.3.4
      - ipython==7.22.0
      - ipywidgets==8.0.4
      - jupyter==1.0.0
      - jupyter-client==7.4.8
      - jupyter-console==6.4.4
      - jupyter-core==5.1.1
      - jupyter-events==0.5.0
      - jupyter-server==2.0.6
      - jupyter-server-terminals==0.4.3
      - jupyterlab-widgets==3.0.5
      - kiwisolver==1.4.4
      - kornia==0.6.8
      - lpips==0.1.3
      - markdown==3.4.1
      - matplotlib==3.4.2
      - nbclassic==0.4.8
      - networkx==2.8.8
      - nibabel==4.0.2
      - notebook==6.5.2
      - notebook-shim==0.2.2
      - omegaconf==2.1.1
      - opencv-python==4.5.1.48
      - pdf2image==1.16.0
      - pip==22.3.1
      - platformdirs==2.6.2
      - prometheus-client==0.15.0
      - protobuf==4.21.9
      - pydeprecate==0.3.2
      - pymupdf==1.21.1
      - pyparsing==3.0.9
      - python-json-logger==2.0.4
      - pywavelets==1.4.1
      - pyyaml==5.4.1
      - pyzmq==24.0.1
      - regex==2022.10.31
      - scikit-image==0.17.2
      - send2trash==1.8.0
      - setuptools==65.6.0
      - sniffio==1.3.0
      - ssim-pil==1.0.14
      - tensorboard==1.15.0
      - tensorboardx==2.1
      - termcolor==2.1.1
      - terminado==0.17.1
      - tifffile==2022.10.10
      - tokenizers==0.12.1
      - torchmetrics==0.7.3
      - tornado==6.2
      - tqdm==4.60.0
      - traitlets==5.8.0
      - transformers==4.19.2
      - websocket-client==1.4.2
      - werkzeug==2.2.2
      - wheel==0.38.4
      - widgetsnbextension==4.0.5
      - zipp==3.10.0
